stages:
- build
- deploy

variables:
  DOCKER_IMAGE: ""
  DOCKER_FILE_NAME: ""
  MANIFEST_STAGING_PATH: ""
  COMMIT_MESSAGE: ""
  GIT_DEPTH: 500  
 

# hidden jobs that can be reuse over other jobs 
.docker_build:
  image: docker:24.0.7
  stage: build
  before_script:
    - docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD
  script:
    - docker  build -t $DOCKER_IMAGE  -f $DOCKER_FILE_NAME .

    - docker push $DOCKER_IMAGE


.update_manifest:
  stage: deploy
  variables:
    MANIFEST_GIT_REPO: https://$USERNAME:$PAT_TOKEN@git.gebeya.training/order-optima/k8s-manifests.git

  before_script:
    - apk add git
    - git clone --single-branch --branch $CI_COMMIT_BRANCH $MANIFEST_GIT_REPO
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
  script:
    - cd k8s-manifests
    # - git remote set-url origin --push $MANIFEST_GIT_REPO
    - git clone --single-branch --branch $CI_COMMIT_BRANCH $MANIFEST_GIT_REPO
    - |
      sed -i "s#image:.*#image: ${DOCKER_IMAGE}#g" ./$MANIFEST_STAGING_PATH
    - git stage ./$MANIFEST_STAGING_PATH
    - git commit -m "$COMMIT_MESSAGE [skip-ci]"
    - git push origin $CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'  
      when: always
    - if: $CI_COMMIT_BRANCH == 'production'
      when: manual
    - when: never 


build_apigateway_service:
  extends: .docker_build
  stage: build
  variables:
    DOCKER_FILE_NAME: "Dockerfile.api"
    IMAGE_PATH: "api-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

build_service_discovery:
  extends: .docker_build
  stage: build
  needs:
    - build_apigateway_service
  variables:
    DOCKER_FILE_NAME: "Dockerfile.discovery"
    IMAGE_PATH: "service-discovery-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

build_auth_service:
  extends: .docker_build
  stage: build
  needs:
    - build_service_discovery
  variables:
    DOCKER_FILE_NAME: "Dockerfile.auth"
    IMAGE_PATH: "auth-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

build_inventory_service:
  extends: .docker_build
  stage: build
  needs:
    - build_auth_service
  variables:
    DOCKER_FILE_NAME: "Dockerfile.inventory"
    IMAGE_PATH: "inventory-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

build_order_service:
  extends: .docker_build
  stage: build
  needs:
    - build_inventory_service
  variables:
    DOCKER_FILE_NAME: "Dockerfile.order"
    IMAGE_PATH: "order-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

build_user_service:
  extends: .docker_build
  stage: build
  needs:
    - build_order_service
  variables:
    DOCKER_FILE_NAME: "Dockerfile.user"
    IMAGE_PATH: "user-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

# update k8s manifest jobs 

update_apigateway_manifest:
  extends: .update_manifest
  stage: deploy
  variables:
    MANIFEST_STAGING_PATH: "api-gateway/deployment.yaml"
    COMMIT_MESSAGE: "update service managmanet image"
    IMAGE_PATH: "api-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

update_service_discovery_manifest:
  extends: .update_manifest
  stage: deploy
  needs:
    - update_apigateway_manifest
  variables:
    MANIFEST_STAGING_PATH: "service-discovery/deployment.yaml"
    COMMIT_MESSAGE: "update service managmanet image"
    IMAGE_PATH: "service-discovery-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA

update_order_service_manifest:
  extends: .update_manifest
  stage: deploy
  needs:
    - update_service_discovery_manifest
  variables:
    MANIFEST_STAGING_PATH: "order-management/deployment.yaml"
    COMMIT_MESSAGE: "update order  managmanet image"
    IMAGE_PATH: "order-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA


update_inventory_service_manifest:
  extends: .update_manifest
  stage: deploy
  needs:
    - update_order_service_manifest
  variables:
    MANIFEST_STAGING_PATH: "inventory-management/deployment.yaml"
    COMMIT_MESSAGE: "update order  inventory image"
    IMAGE_PATH: "inventory-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA



update_auth_service-manifest:
  extends: .update_manifest
  stage: deploy
  needs:
    - update_inventory_service_manifest
  variables:
    MANIFEST_STAGING_PATH: "auth-service/deployment.yaml"
    COMMIT_MESSAGE: "update auth service image"
    IMAGE_PATH: "auth-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA
    
update_user_service-manifest:
  extends: .update_manifest
  stage: deploy
  needs:
    - update_auth_service-manifest
  variables:
    MANIFEST_STAGING_PATH: "user-service/deployment.yaml"
    COMMIT_MESSAGE: "update auth service image"
    IMAGE_PATH: "user-service-"
    DOCKER_IMAGE: $DOCKER_USER_NAME/${IMAGE_PATH}${CI_PROJECT_NAME}:$CI_COMMIT_SHORT_SHA
