
FROM maven:3.8.4-openjdk-17-slim AS build

WORKDIR /app


COPY pom.xml .
COPY api-gateway/pom.xml ./api-gateway/


COPY api-gateway/src ./api-gateway/src


RUN mvn clean install -f api-gateway/pom.xml -DskipTests


FROM openjdk:17-jdk-alpine


WORKDIR /app


COPY --from=build /app/api-gateway/target/api-gateway.jar ./api-gateway.jar

EXPOSE 8181

CMD ["java", "-jar", "api-gateway.jar"]