
FROM maven:3.8.4-openjdk-17-slim AS build

# RUN apt-get update && apt-get install -y git

WORKDIR /app


COPY pom.xml .
COPY api-gateway/pom.xml ./api-gateway/


COPY api-gateway/src ./api-gateway/src


RUN mvn clean install -f api-gateway/pom.xml -DskipTests


FROM openjdk:17-jdk-alpine


WORKDIR /app


COPY --from=build /app/api-gateway/target/api-gateway-0.0.1-SNAPSHOT.jar  ./api-gateway-0.0.1-SNAPSHOT.jar 

EXPOSE 8181

CMD ["java", "-jar", "api-gateway-0.0.1-SNAPSHOT.jar "]