
spring:
  application:
    name: service-discovery

server:
  port: 8761

eureka:
  instance:
    hostname: ${spring.application.name}
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    




